In [306]:
import pandas as pd
import numpy as  np

In [307]:
data=pd.read_csv('Advertising_data.csv')

In [308]:
data.head()

User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [309]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
#le.fit(["Male","Female"])
data['Gender']=le.fit_transform(data['Gender'])

In [310]:
data

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510       1  19.0          19000.0          0
1    15810944       1  35.0          20000.0          0
2    15668575       0  26.0          43000.0          0
3    15603246       0  27.0          57000.0          0
4    15804002       1  19.0          76000.0          0
5    15728773       1  27.0          58000.0          0
6    15598044       0  27.0          84000.0          0
7    15694829       0  32.0         150000.0          1
8    15600575       1  25.0          33000.0          0
9    15727311       0  35.0          65000.0          0
10   15570769       0  26.0          80000.0          0
11   15606274       0  26.0          52000.0          0
12   15746139       1  20.0          86000.0          0
13   15704987       1  32.0          18000.0          0
14   15628972       1  18.0          82000.0          0
15   15697686       1  29.0          80000.0          0
16   15733883       1  47.0          25000.0          1
17   15617482       1  45.0          26000.0          1
18   15704583       1  46.0          28000.0          1
19   15621083       0  48.0          29000.0          1
20   15649487       1  45.0          22000.0          1
21   15736760       0  47.0          49000.0          1
22   15714658       1  48.0          41000.0          1
23   15599081       0  45.0          22000.0          1
24   15705113       1  46.0          23000.0          1
25   15631159       1  47.0          20000.0          1
26   15792818       1  49.0          28000.0          1
27   15633531       0  47.0          30000.0          1
28   15744529       1  29.0          43000.0          0
29   15669656       1  31.0          18000.0          0
..        ...     ...   ...              ...        ...
370  15611430       0  60.0          46000.0          1
371  15774744       1  60.0          83000.0          1
372  15629885       0  39.0          73000.0          0
373  15708791       1  59.0         130000.0          1
374  15793890       0  37.0          80000.0          0
375  15646091       0  46.0          32000.0          1
376  15596984       0  46.0          74000.0          0
377  15800215       0  42.0          53000.0          0
378  15577806       1  41.0          87000.0          1
379  15749381       0  58.0          23000.0          1
380  15683758       1  42.0          64000.0          0
381  15670615       1  48.0          33000.0          1
382  15715622       0  44.0         139000.0          1
383  15707634       1  49.0          28000.0          1
384  15806901       0  57.0          33000.0          1
385  15775335       1  56.0          60000.0          1
386  15724150       0  49.0          39000.0          1
387  15627220       1  39.0          71000.0          0
388  15672330       1  47.0          34000.0          1
389  15668521       0  48.0          35000.0          1
390  15807837       1  48.0          33000.0          1
391  15592570       1  47.0          23000.0          1
392  15748589       0  45.0          45000.0          1
393  15635893       1  60.0          42000.0          1
394  15757632       0  39.0          59000.0          0
395  15691863       0  46.0          41000.0          1
396  15706071       1  51.0          23000.0          1
397  15654296       0  50.0          20000.0          1
398  15755018       1  36.0          33000.0          0
399  15594041       0  49.0          36000.0          1

[400 rows x 5 columns]

In [311]:
data=data.reset_index()

In [312]:
data.drop(columns='User ID',inplace=True,axis=1)

In [313]:
del data['index']

In [314]:
X=data.iloc[:,:-1].values

In [315]:
y=data.iloc[:,-1].values

In [316]:
X

array([[1.0e+00, 1.9e+01, 1.9e+04],
       [1.0e+00, 3.5e+01, 2.0e+04],
       [0.0e+00, 2.6e+01, 4.3e+04],
       ...,
       [0.0e+00, 5.0e+01, 2.0e+04],
       [1.0e+00, 3.6e+01, 3.3e+04],
       [0.0e+00, 4.9e+01, 3.6e+04]])

In [317]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [318]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [319]:
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [320]:
X_train

array([[-0.98019606,  0.58164944, -0.88670699],
       [ 1.02020406, -0.60673761,  1.46173768],
       [-0.98019606, -0.01254409, -0.5677824 ],
       [-0.98019606, -0.60673761,  1.89663484],
       [-0.98019606,  1.37390747, -1.40858358],
       [-0.98019606,  1.47293972,  0.99784738],
       [ 1.02020406,  0.08648817, -0.79972756],
       [ 1.02020406, -0.01254409, -0.24885782],
       [-0.98019606, -0.21060859, -0.5677824 ],
       [-0.98019606, -0.21060859, -0.19087153],
       [-0.98019606, -0.30964085, -1.29261101],
       [ 1.02020406, -0.30964085, -0.5677824 ],
       [ 1.02020406,  0.38358493,  0.09905991],
       [-0.98019606,  0.8787462 , -0.59677555],
       [-0.98019606,  2.06713324, -1.17663843],
       [ 1.02020406,  1.07681071, -0.13288524],
       [-0.98019606,  0.68068169,  1.78066227],
       [-0.98019606, -0.70576986,  0.56295021],
       [-0.98019606,  0.77971394,  0.35999821],
       [-0.98019606,  0.8787462 , -0.53878926],
       [ 1.02020406, -1.20093113, -1.582

In [321]:
X_test

array([[ 1.02020406, -0.54748976,  0.5130727 ],
       [-0.98019606,  0.15442019, -0.61825566],
       [ 1.02020406, -0.10879604,  0.14615539],
       [-0.98019606, -0.54748976,  0.26846116],
       [-0.98019606, -0.10879604, -0.61825566],
       [ 1.02020406, -0.81070599, -1.53554892],
       [-0.98019606, -0.45975102, -1.68843113],
       [ 1.02020406, -0.0210573 ,  2.25592989],
       [-0.98019606, -1.60035469, -0.0678797 ],
       [ 1.02020406,  0.94406888, -0.83229075],
       [ 1.02020406, -0.54748976, -0.6488321 ],
       [-0.98019606, -0.72296725, -0.46537345],
       [ 1.02020406,  0.06668145, -0.46537345],
       [ 1.02020406,  0.24215893,  0.20730828],
       [ 1.02020406, -1.4248772 ,  0.48249625],
       [-0.98019606, -0.37201227,  1.43036596],
       [ 1.02020406,  0.06668145,  0.20730828],
       [ 1.02020406, -1.51261594,  0.45191981],
       [-0.98019606,  1.64597884,  1.8278597 ],
       [ 1.02020406, -0.10879604, -1.47439603],
       [-0.98019606, -0.10879604, -0.709

In [322]:
from sklearn.svm import SVC
svmachine=SVC(kernel='rbf',random_state=0,C=1)
svmachine.fit(X_train,y_train)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [323]:
predicted=svmachine.predict(X_test)

In [324]:
predicted

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [325]:
#from sklearn import metrics
score=svmachine.score(X_test,y_test)

In [326]:
score*100

93.0

In [327]:
from sklearn.model_selection import GridSearchCV
paramters=[{'C':[1,10,100,1000],'kernel':['linear']},{'C':[1,10,100,1000],'kernel':['rbf'],'gamma':[0.1,0.2,0.3,0.4,0.5,0.5,0.7,0.8,0.9]}]

In [328]:
grid_search=GridSearchCV(estimator=svmachine,param_grid=paramters,scoring='accuracy',cv=10,n_jobs=-1)


In [329]:
grid_search=grid_search.fit(X_train,y_train)

In [330]:
accurac=grid_search.best_score_

In [331]:
accurac

0.9033333333333333

In [332]:
grid_search.best_params_

{'C': 1, 'gamma': 0.3, 'kernel': 'rbf'}

In [333]:
svmachine2=SVC(kernel='rbf',gamma=0.7,C=1)
svmachine2.fit(X_train,y_train)
score=svmachine2.score(X_test,y_test)
y_pred=svmachine2.predict(X_test)

In [334]:
score

0.93

In [335]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [336]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)

In [337]:
accuracy

0.93